import "./style.css";
import PopularList from "../../Components/PopularList";
import ExploreList from "../../Components/ExploreList";

const sections = [
  {
    type: "popular",
    title: "cuisines",
    links: [
      { label: "Bakery food", to: "/" },
      { label: "Beverages food", to: "/" },
      { label: "Biryani food", to: "/" },
      { label: "Burger food", to: "/" },
      { label: "Chinese food", to: "/" },
      { label: "Continental food", to: "/" },
      { label: "Desserts food", to: "/" },
      { label: "Ice Cream food", to: "/" },
      { label: "Italian food", to: "/" },
      { label: "Kebab food", to: "/" },
      { label: "Mithai food", to: "/" },
      { label: "Momos food", to: "/" },
      { label: "Mughali food", to: "/" },
      { label: "North Indian food", to: "/" },
      { label: "Pizza food", to: "/" },
      { label: "Rolls food", to: "/" },
      { label: "Sandwich food", to: "/" },
      { label: "Shake food", to: "/" },
      { label: "South Indian food", to: "/" },
      { label: "Street food", to: "/" },
    ],
  },
  {
    type: "popular",
    title: "restaurant types",
    links: [
      { label: "Bakeries", to: "/" },
      { label: "Bakery Stores", to: "/" },
      { label: "Bars", to: "/" },
      { label: "Beverage Shops", to: "/" },
      { label: "Bhojanalya", to: "/" },
      { label: "Cafes", to: "/" },
      { label: "Casual Dining", to: "/" },
      { label: "Clubs", to: "/" },
      { label: "Cocktail Bars", to: "/" },
      { label: "Confectioneries", to: "/" },
      { label: "Dairy", to: "/" },
      { label: "Dessert Parlors", to: "/" },
      { label: "Dhabas", to: "/" },
      { label: "Fine Dining", to: "/" },
      { label: "Food Courts", to: "/" },
      { label: "Food Trucks", to: "/" },
      { label: "Irani Cafes", to: "/" },
      { label: "Kiosks", to: "/" },
      { label: "Lounges", to: "/" },
      { label: "Meat Shops", to: "/" },
      { label: "Microbreweries", to: "/" },
      { label: "Paan Shops", to: "/" },
      { label: "Pubs", to: "/" },
      { label: "Quick Bites", to: "/" },
      { label: "Sweet Shops", to: "/" },
    ],
  },
  {
    type: "explore",
    title: "Top Restaurant Chains",
    links: [
      { label: "Bikanervala", to: "/" },
      { label: "Biryani Blues", to: "/" },
      { label: "BTW", to: "/" },
      { label: "Burger King", to: "/" },
      { label: "Burger Singh", to: "/" },
      { label: "Domino's", to: "/" },
      { label: "Dunkin' Donuts", to: "/" },
      { label: "Faasos", to: "/" },
      { label: "Haldiram's", to: "/" },
      { label: "KFC", to: "/" },
      { label: "Krispy Kreme", to: "/" },
      { label: "McDonald's", to: "/" },
      { label: "Moti Mahal Delux", to: "/" },
      { label: "Om Sweets & Snacks", to: "/" },
      { label: "Paradise Biryani", to: "/" },
      { label: "Pizza Hut", to: "/" },
      { label: "Sagar Ratna", to: "/" },
      { label: "Subway", to: "/" },
      { label: "WOW! Momo", to: "/" },
    ],
  },
  {
    type: "explore",
    title: "Cities We Deliver To",
    links: [
      { label: "Delhi NCR", to: "/" },
      { label: "Kolkata", to: "/" },
      { label: "Mumbai", to: "/" },
      { label: "Pune", to: "/" },
      { label: "Hyderabad", to: "/" },
      { label: "Chennai", to: "/" },
      { label: "Lucknow", to: "/" },
      { label: "Kochi", to: "/" },
      { label: "Jaipur", to: "/" },
      { label: "Ahmedabad", to: "/" },
      { label: "Chandigarh", to: "/" },
      { label: "Goa", to: "/" },
      { label: "Indore", to: "/" },
      { label: "Nashik", to: "/" },
      { label: "Ooty", to: "/" },
      { label: "Shimla", to: "/" },
      { label: "Ludhiana", to: "/" },
      { label: "Guwahati", to: "/" },
      { label: "Amritsar", to: "/" },
      { label: "Kanpur", to: "/" },
      { label: "Allahabad", to: "/" },
      { label: "Aurangabad", to: "/" },
      { label: "Bhopal", to: "/" },
      { label: "Ranchi", to: "/" },
      { label: "Visakhapatnam", to: "/" },
      { label: "Bhubaneswar", to: "/" },
      { label: "Coimbatore", to: "/" },
      { label: "Mangalore", to: "/" },
      { label: "Vadodara", to: "/" },
      { label: "Nagpur", to: "/" },
      { label: "Agra", to: "/" },
      { label: "Dehradun", to: "/" },
      { label: "Mysore", to: "/" },
      { label: "Puducherry", to: "/" },
      { label: "Surat", to: "/" },
      { label: "Varanasi", to: "/" },
      { label: "Patna", to: "/" },
      { label: "Udaipur", to: "/" },
      { label: "Cuttack", to: "/" },
      { label: "Trivandrum", to: "/" },
      { label: "Haridwar", to: "/" },
      { label: "Leh", to: "/" },
      { label: "Pushkar", to: "/" },
      { label: "Rajkot", to: "/" },
      { label: "Madurai", to: "/" },
      { label: "Kozhikode", to: "/" },
      { label: "Alappuzha", to: "/" },
      { label: "Thrissur", to: "/" },
      { label: "Manipal", to: "/" },
      { label: "Vajayawada", to: "/" },
      { label: "Jodhpur", to: "/" },
      { label: "Kota", to: "/" },
      { label: "Ajmer", to: "/" },
      { label: "Mussorie", to: "/" },
      { label: "Rishikesh", to: "/" },
      { label: "Jalandhar", to: "/" },
      { label: "Jammu", to: "/" },
      { label: "Manali", to: "/" },
      { label: "Dharamshala", to: "/" },
      { label: "Raipur", to: "/" },
      { label: "Gorakhpur", to: "/" },
      { label: "Palakkad", to: "/" },
      { label: "See more", to: "/", class: "more" },
    ],
  },
];

const ExploreOptions = () => {
  return (
    <section className="exploreOptions">
      <div className="set-width">
        <h3 className="explore-title">Explore other Options for you here</h3>

        {sections.map((section, index) => (
          <div key={index} className="explore-section-wrapper">
            {section.type === "popular" ? <PopularList title={section.title} links={section.links} /> : <ExploreList title={section.title} links={section.links} />}
          </div>
        ))}
      </div>
    </section>
  );
};

export default ExploreOptions;
